-- Platform - Supabase hardening after Sequelize creates the schema.
-- Run this in Supabase SQL Editor after the first controlled deploy.

create extension if not exists vector;
create extension if not exists pgcrypto;

-- Helpful indexes for tenant-scoped workloads. Sequelize also creates several
-- indexes, but these are safe to keep explicit in Supabase.
create index if not exists contacts_workspace_updated_idx on "Contacts" ("workspaceId", "updatedAt" desc);
create index if not exists messages_workspace_created_idx on "Messages" ("workspaceId", "createdAt" desc);
create index if not exists webhook_events_workspace_created_idx on "WebhookEvents" ("workspaceId", "eventType", "createdAt" desc);
create index if not exists chats_workspace_status_idx on "Chats" ("workspaceId", "status", "lastMessageAt" desc);
create index if not exists broadcasts_workspace_status_idx on "Broadcasts" ("workspaceId", "status");
create index if not exists broadcast_recipients_due_idx on "BroadcastRecipients" ("workspaceId", "status", "scheduledAt");
create index if not exists sequence_enrollments_due_idx on "SequenceEnrollments" ("workspaceId", "status", "nextRunAt");
create index if not exists ai_agents_workspace_default_idx on "AiAgents" ("workspaceId", "isDefault");
create index if not exists integration_servers_workspace_active_idx on "IntegrationServers" ("workspaceId", "active");
create index if not exists integration_servers_workspace_provider_idx on "IntegrationServers" ("workspaceId", "provider");

-- After confirming every row has workspaceId, enforce tenant ownership.
alter table "Contacts" alter column "workspaceId" set not null;
alter table "Flows" alter column "workspaceId" set not null;
alter table "FlowSessions" alter column "workspaceId" set not null;
alter table "Sequences" alter column "workspaceId" set not null;
alter table "SequenceSteps" alter column "workspaceId" set not null;
alter table "SequenceEnrollments" alter column "workspaceId" set not null;
alter table "Broadcasts" alter column "workspaceId" set not null;
alter table "BroadcastRecipients" alter column "workspaceId" set not null;
alter table "Attendants" alter column "workspaceId" set not null;
alter table "Chats" alter column "workspaceId" set not null;
alter table "Messages" alter column "workspaceId" set not null;
alter table "WebhookEvents" alter column "workspaceId" set not null;
alter table "RagDocuments" alter column "workspaceId" set not null;
alter table "RagChunks" alter column "workspaceId" set not null;
alter table "AiAgents" alter column "workspaceId" set not null;
alter table "IntegrationServers" alter column "workspaceId" set not null;

-- Optional RLS foundation. The current Express API uses service credentials and
-- already scopes every query by workspaceId. Enable these policies only if you
-- expose tables through Supabase Auth/PostgREST directly.
alter table "Workspaces" enable row level security;
alter table "Contacts" enable row level security;
alter table "Flows" enable row level security;
alter table "FlowSessions" enable row level security;
alter table "Sequences" enable row level security;
alter table "SequenceSteps" enable row level security;
alter table "SequenceEnrollments" enable row level security;
alter table "Broadcasts" enable row level security;
alter table "BroadcastRecipients" enable row level security;
alter table "Attendants" enable row level security;
alter table "Chats" enable row level security;
alter table "Messages" enable row level security;
alter table "WebhookEvents" enable row level security;
alter table "RagDocuments" enable row level security;
alter table "RagChunks" enable row level security;
alter table "AiAgents" enable row level security;
alter table "IntegrationServers" enable row level security;

-- Future Supabase Auth bridge:
-- Store workspace_id in JWT app_metadata and set it as a claim.
-- Then policies can use:
--   (auth.jwt() ->> 'workspace_id')::int = "workspaceId"
--
-- Example policy pattern for tenant tables:
-- create policy contacts_workspace_select on "Contacts"
-- for select
-- using ((auth.jwt() ->> 'workspace_id')::int = "workspaceId");

-- pgvector table for future RAG. Keep separate from RagChunks until embeddings
-- are generated by a worker.
create table if not exists "RagEmbeddings" (
  id bigserial primary key,
  "workspaceId" integer not null references "Workspaces"(id) on delete cascade,
  "ragChunkId" integer references "RagChunks"(id) on delete cascade,
  content text not null,
  embedding vector(1536),
  metadata jsonb not null default '{}',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create index if not exists rag_embeddings_workspace_idx on "RagEmbeddings" ("workspaceId");
create index if not exists rag_embeddings_vector_idx on "RagEmbeddings" using ivfflat (embedding vector_cosine_ops);
